version: '3.8'

services:
    db:
        image: postgres:15-alpine
        container_name: kastamonudb
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: mostar
            POSTGRES_PASSWORD: viyanakapilari
            POSTGRES_DB: kast_url
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
